apiVersion: v1
kind: Pod
metadata:
  name: kubedemo-pod
  labels:
    project: kube-demo
spec:
  containers:
    - name: kubedemo
      image: ankur2411/kubedemo:2.0
      ports:
        - containerPort: 8080