{{- if .Values.securitySecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubedemo.fullname" . }}-security
type: Opaque
stringData:
  SECURITY_USERS: {{ .Values.securitySecret.securityUsers | quote }}
{{- end }}
