apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedemo.fullname" . }}
  labels:
    {{ include "kubedemo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "kubedemo.fullname" . }}
