apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedemo-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      project: kube-demo
  minReadySeconds: 20 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels: 
        project: kube-demo
    spec:
      containers:
      - name: kubedemo
        imagePullPolicy: Always
        image: ankur2411/kubedemo:3.0
        ports:
        - containerPort: 8080