replicaCount: 5

image:
  repository: ankur2411/kube-demo
  tag: "2.0.2"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

securitySecret:
  create: false
  name: "kubedemo-security"
  key: "SECURITY_USERS"
  securityUsers: ""

livenessProbe:
  path: /health/liveness
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /health/readiness
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
